### ISSUE TITLE
Error: Non-whitespace before first tag.

### ISSUE THREAD

**Issue by mnpenner** [nolanlawson/rollup-plugin-svg-to-jsx#1]
I'm getting this error:

```
{ Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: R
    at error (/home/me/Projects/proj/node_modules/rollup/dist/rollup.js:189:14)
    at Promise.resolve.then.catch.err (/home/me/Projects/proj/node_modules/rollup/dist/rollup.js:17593:6)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'PLUGIN_ERROR',
  plugin: undefined,
  id: '/home/me/Projects/proj/src/icons/sort.svg' }
```

on an SVG that starts like:

```svg
<svg xmlns="http://www.w3.org/2000/svg" ...
```
There doesn't appear to be any non-whitespace chars before `<svg`. What gives?

**Comment by nolanlawson** [comment]
Can you provide the full SVG and/or steps to repro?

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if this is still a problem
